MLSysOps/MLE-agent

agent/function/plan_agent.py

Closes https://github.com/MLSysOps/MLE-agent/issues/71
1. enhance the prompts to strickly follow the filename output format;
2. add the filename as candidate lists if the output is a single string.
We should let the agent to generate the filename candidates in the correct format.
[? What is the description of this project? (Optional)] train vit using mnist
[? Hi, what are your requirements?] train vit using mnist datasets
No

[MRG] quickfix: filename generating in wrong format

---

agent/function/tech_leader.py
agent/utils/__init__.py
agent/utils/display.py
requirements.txt

Closes https://github.com/MLSysOps/MLE-agent/issues/70
Displaying the task plannings as DAG cards may make it clearer for users to see the agent’s future processes.
No
No

[MRG] feat: display planning as the DAG cards

---

README.md
mle/agents/advisor.py
mle/agents/coder.py
mle/agents/planner.py
mle/workflow/baseline.py

___
Enhancement
___
- Refactored the display format of suggestions in `process_report` function using `[green]` tags for better readability.
- Updated the status message in `AdviseAgent.suggest` method to be more descriptive.
- Refactored dataset information display in `ask_data` function using `[green]` tags.
- Updated the prompt for dataset information in `baseline` function for clarity.
- Modified advisor report generation in `baseline` function to include formatted user requirements.
___
<tr>
<td>
<details> …

[MRG] refactor the displayed info, fix small UI issues

---

README.md

Closes #
___
documentation
___
- Added new milestone dates for v0.3.0 and v0.2.0 releases.
- Included instructions for installing the package from source.
- Removed the example user requirements section to streamline the README.
___
<tr>
<td>
<details>
<summary><strong>README.md</strong><dd><code>Update README with milestones and installation instructions</code></dd></summary>
<hr>
README.md
<li>Added new milestone dates for v0.3.0 and v0.2.0 releases.<br> <li> Added instructions for installing from source.<br> <li> Removed example user requirements …

Update README.md for v030

---

mle/version.py

enhancement
___
- Updated the `__version__` variable in `mle/version.py` from '0.3.0' to '0.3.1'.
___
<tr>
<td>
<details>
<summary><strong>version.py</strong><dd><code>Bump version to 0.3.1</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
mle/version.py
- Updated the `__version__` variable from '0.3.0' to '0.3.1'.
</details>
</td>
<td><a href="https://github.com/MLSysOps/MLE-agent/pull/124/files#diff-acd9c1d9e32245b0d91b94eb263169 …

[MRG] 👷 build: 0.3.1

---

README.md

Closes #
___
documentation
___
- Added a new "Star History" section to the README.md file.
- Included a Star History Chart that links to star-history.com for visualizing the repository's star history.
___
<tr>
<td>
<details>
<summary><strong>README.md</strong><dd><code>Add Star History section with chart</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
README.md
<li>Added a new section for Star History.<br> <li> Included a …

[MRG] add star history

---

requirements.txt

enhancement
___
- Removed the specific version constraint for `setuptools` in `requirements.txt`, allowing for the latest version to be used.
___
<tr>
<td>
<details>
<summary><strong>requirements.txt</strong><dd><code>Remove specific version constraint for setuptools</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
requirements.txt
<li>Removed specific version constraint for <code>setuptools</code>.<br> <li> Changed <code>setuptools</code> to have no specific version, allowing for the <br>latest version to be used.<br>
</details>
</td>
<td><a href="https://github.com/MLSysOps/MLE-agent/pull/135/files#diff-4d7c51b1efe9043e4 …

[MRG] Upgrade setuptools

---

.gitignore
mle/workflow/baseline.py

___
enhancement
___
- Improved user prompts to provide clearer instructions for resuming steps and providing requirements.
- Updated step descriptions to better reflect the actions being performed by various agents.
- Enhanced debugging status messages to specify the role of the MLE Debug Agent.
___
<tr>
<td>
<details>
<summary><strong>baseline.py</strong><dd><code>Improve user interaction and step descriptions in baseline workflow</code></dd></summary>
<hr>
mle/workflow/baseline.py
<li>Improved user prompts for clarity.<br> <li> Updated step descriptions …

[MRG] fix typos

---

mle/integration/google_calendar.py

docs: update google_calendar.py

---

mle/cli.py
mle/model.py
mle/workflow/baseline.py
mle/workflow/kaggle.py
mle/workflow/report.py

closes https://github.com/MLSysOps/MLE-agent/issues/153

[MRG] add claude model support

---

mle/agents/summarizer.py
mle/cli.py
mle/function/__init__.py
mle/function/search.py
mle/integration/github.py
mle/model.py
mle/workflow/__init__.py
mle/workflow/kaggle.py
mle/workflow/report.py

We need to update the Github integration function as well, I will do this in the same PR
___
enhancement
___
- Introduced a new `SummaryAgent` class in `mle/agents/summarizer.py` to summarize GitHub projects, including project information, structure, issues, and source code.
- Implemented a `summary` method to interact with a model and return project summaries in JSON format.
- Added comments in `mle/function/__init__.py` for a new GitHub integration function schema, preparing for future enhancements.
___
<tr>
<td>
<details>
<summary><strong>summarizer.py</strong><dd><code>Added `SummaryAgent` class for GitHub project summarization</code></dd></summary> …

[MRG] added the summary agent

---

mle/cli.py
mle/workflow/report.py

closes: https://github.com/MLSysOps/MLE-agent/issues/164
```
$ mle report MLSysOps/MLE-agent
```

[MRG] support `mle report <org/repo>` command

---

CONTRIBUTING.md
mle/workflow/report.py

RT
___
Documentation
___
- Updated the `CONTRIBUTING.md` file with detailed guidelines for contributing to the project, including instructions on submitting pull requests, the review process, and triaging issues.
- Removed unused imports from `mle/workflow/report.py` to clean up the code.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Miscellaneous</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>report.py</strong><dd><code>Clean up unused imports in report module</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
mle/workflow/report.py
- Removed unused imports: `json` and `print_in_box`.
</details>
</td>
<td><a …

[MRG] updated the docs of contributing

---

mle/agents/reporter.py
mle/agents/summarizer.py
mle/cli.py
mle/server/app.py
mle/workflow/report.py
web/app/page.tsx
web/package.json
web/pnpm-lock.yaml

1. `mle new <project_name>`
2. `cd <project_name>`
3. run `mle integrate`, to integrate with your Github
4. run `mle serve` to start the server
1. `cd <MLE-Agent>/web` to enter the web source code folder
2. `pnpm I & pnpm run dev` to start the local web UI
___
Enhancement, Bug fix
___
- Enhanced the report generation process with more detailed sections and improved filtering of Google Calendar events.
- Added both synchronous and asynchronous endpoints for report generation in the server application, with error handling.
- Improved the web UI by adding a loading spinner and better feedback messages during report generation.
- Simplified the report generation function in the workflow module to directly return the report.
- Removed the GitHub username prompt from the CLI integration setup. …

[MRG] Improve the web UI to use the sync backend API

---

mle/agents/reporter.py
web/app/page.tsx

Closes #180
___
Bug fix, Enhancement
___
- Added error handling for when no report is found (404 status) in the `fetchLatestReport` function, providing a user-friendly message.
- Enhanced the UI by updating the labels and buttons for additional data sources, including links to RepX PRO for integration.
- Removed the "Save Report" button from the form to streamline the user interface.
___
<tr>
<td>
<details>
<summary><strong>page.tsx</strong><dd><code>Improved error handling and UI enhancements in report generation</code></dd></summary>
<hr>
web/app/page.tsx
<li>Added error handling for 404 status in <code>fetchLatestReport</code> function.<br> <li> …

[MRG] Fixed the UI bug of no report generation

---

mle/agents/advisor.py
mle/cli.py

Closes #188
___
enhancement, bug fix
___
- Clarified the conditions under which the `preview_csv_data` function should be used for public datasets in the advisor documentation.
- Changed the default mode in the CLI from 'general' to 'baseline' to better align with the intended functionality.
- Updated the error message in the CLI to reflect the new mode options, ensuring users are informed of valid modes.
___
<tr>
<td>
<details>
<summary><strong>advisor.py</strong><dd><code>Clarify dataset preview conditions in advisor documentation</code></dd></summary>
<hr>
mle/agents/advisor.py
<li>Clarified the usage of <code>preview_csv_data</code> for public …

[MRG] fix prevewing public dataset errors

---

mle/cli.py
mle/model.py
mle/utils/memory.py
mle/utils/system.py
mle/workflow/report.py

closes: https://github.com/MLSysOps/MLE-agent/issues/158

[MRG] move config file into `.mle`

---

mle/cli.py
mle/function/data.py
mle/integration/__init__.py
mle/integration/kaggle.py
mle/model.py
mle/workflow/__init__.py
mle/workflow/kaggle.py

Closes https://github.com/MLSysOps/MLE-agent/issues/178

[MRG] add `mle kaggle` pipeline

---

mle/model.py

As noted in #173, using the llama model may result in non-JSON formatted responses in certain scenarios.
- [*] confirmed all checks still pass OR confirm CI build passes.
- [*] verified that any code or assets from external sources are properly credited in comments and/or in

[MRG] fix ollama output without json format

---

web/app/page.tsx

RT
___
enhancement
___
- Added the `DiscordOutlined` icon to the import list to enhance the UI with a new icon for the Feedback button.
- Replaced the `MailOutlined` icon with `DiscordOutlined` for the Feedback button to better represent the Discord link.
- Updated the URL associated with the `XOutlined` icon to point to a new Twitter handle.
___
<tr>
<td>
<details>
<summary><strong>page.tsx</strong><dd><code>Update UI icons and URLs in the navigation bar</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
web/app/page.tsx
<li>Added <code>DiscordOutlined</code> icon to the import statement.<br> <li> …

[MRG] fix UI icons

---

mle/agents/advisor.py
mle/agents/planner.py
mle/cli.py
mle/model.py
mle/utils/__init__.py
mle/utils/data.py
mle/workflow/baseline.py

- Added support for MistralAI SDK
- The Mistral model (test with - mistral-large-latest) doesn't always return json, so also added a function to use regex to get proper json.
- Also found a bug here - https://github.com/MLSysOps/MLE-agent/blob/8109d8b905bb4aac4de6258516a966abaf2147f5/mle/agents/advisor.py#L188 - currently when providing a dataset its getting set to 'None'

[MRG] Add mistralai support

---

mle/cli.py
mle/model.py

[MRG] deepseek support

---

mle/agents/summarizer.py
mle/workflow/kaggle.py

Closes https://github.com/MLSysOps/MLE-agent/issues/206

[MRG] add kaggle requirement summary

---

README.md

closes: https://github.com/MLSysOps/MLE-agent/issues/210

[MRG] update README.md with kaggle and report mode

---

mle/cli.py
mle/utils/cache.py

related to: https://github.com/MLSysOps/MLE-agent/issues/205

[MRG] inject the project info into chat system prompt

---

mle/utils/system.py

Closes https://github.com/MLSysOps/MLE-agent/issues/220

[MRG] add check for config file

---

mle/integration/github.py

Closes https://github.com/MLSysOps/MLE-agent/issues/203

[MRG] fix github integration to fetch `master` branch

---

mle/agents/advisor.py
mle/agents/summarizer.py
mle/workflow/kaggle.py

`precise` mode is more suitable for a task with clear metrics and datasets.
Here is an example of using `auto_kaggle` to complete a Kaggle competition:
```sh
mle kaggle --auto \
--datasets "/Users/huangyz0918/Library/Caches/mle-bench/data/spooky-author-identification/prepared/public/train.csv,/Users/huangyz0918/Library/Caches/mle-bench/data/spooky-author-identification/prepared/public/test.csv" \
--description "/Users/huangyz0918/Library/Caches/mle-bench/data/spooky-author-identification/prepared/public/description.md" \
--submission "/Users/huangyz0918/desktop/test-kaggle3/submission.csv" \
--sub_example "/Users/huangyz0918/Library/Caches/mle-bench/data/spooky-author-identification/prepared/public/sample_submission.csv" \
--comp_id "spooky-author-identification"
```
FYI @leeeizhang

[MRG] Update the advisor to support various modes

---

README.md

[MRG] Updated the readme with v0.4.2

---

mle/function/data.py

Enhances the `preview_csv_data` function to provide a more comprehensive summary of csv files:
- adding `column types` to the preview summary
- including the count of `NaN` values to assist in handling these fields during code generation
- adding `examples` for each column
- including `data ranges` for numeric data types
Before:
```
Data file: /mnt/data00/mle-bench/spaceship-titanic/prepared/public/train.csv
Number of all rows: 7823
All columns: PassengerId, HomePlanet, CryoSleep, Cabin, Destination, Age, VIP, RoomService, FoodCourt, ShoppingMall, Spa, VRDeck, Name, Transported
Data example:
{'PassengerId': '4408_01', 'HomePlanet': 'Mars', 'CryoSleep': True, 'Cabin': 'F/906/P', 'Destination': 'TRAPPIST-1e', 'Age': 75.0, 'VIP': False, 'RoomService': 0.0, 'FoodCourt': 0.0, 'ShoppingMall': …
```

[MRG] update the preview_csv_data function

---

mle/function/files.py

```python3
from mle.function import list_files
print(list_files("./", max_depth=3, max_items=5)) # its return will never exceed (max_items ^ max_depth) + 1 lines
```
```
/root/workspace/MLE-agent
│── dist/  (0 directories, 1 files)
│   └── mle_agent-0.3.1-py3-none-any.whl (303,703 bytes)
│── assets/  (0 directories, 1 files)
│   └── kaia_llama.webp (93,848 bytes)
│── web/  (5 directories, 11 files)
│   │── app/  (1 directories, 3 files)
│   │── .next/  (4 directories, 5 files)
│   │── public/  (3 directories, 2 files)
│   │── src/  (6 directories, 0 files)
│   │── node_modules/  (28 directories, 1 files)
│   │── next.config.mjs (92 bytes)
│   │── postcss.config.mjs (135 bytes)
│   │── tsconfig.json (26 lines)
│   │── .gitignore (391 bytes)
│   │── package-lock.json (7963 lines)
│   └── …
```

[MRG] enhance `list_files` function

---

mle/agents/coder.py
mle/function/__init__.py
mle/function/data.py
mle/function/execution.py
mle/function/files.py

[MRG] Improve data operation functions

---

mle/integration/kaggle.py
requirements.txt

[MRG] quickfix: missing imports and some bugs

---

README.md
mle/agents/summarizer.py
mle/cli.py
mle/integration/local_git.py
mle/workflow/__init__.py
mle/workflow/kaggle.py
mle/workflow/report.py
mle/workflow/report_local.py

Closes #244 
```bash
cd <project name>
mle report-local --email=<git email> --start-date=YYYY-MM-DD --end-date=YYYY-MM-DD <path_to_git_repo>
```
- `--start-date` and `--end-date` are optional parameters. If omitted, the command will generate a report for the default date range of the last 7 days.
- Replace `<git email>` with your Git email and `<path_to_git_repo>` with the path to your local Git repository.

[MRG] Add a command to generate report for local git repository

---

mle/agents/coder.py
mle/cli.py
mle/function/search.py
mle/model/__init__.py
mle/model/gemini.py

Closes  https://github.com/MLSysOps/MLE-agent/issues/166

[MRG] add gemini model

---

mle/cli.py
mle/utils/memory.py
requirements.txt

related to: https://github.com/MLSysOps/MLE-agent/issues/259
```python3
$ cd /path/to/mle/project
$ python3
>>> from mle.utils import LanceDBMemory
>>> memory = LanceDBMemory("./")
>>> memory.add("hello world", metadata={"path": "/path/to/file"})
['deff1675-41ac-4190-b3b6-7ca9fde85c59']
>>> memory.query("hi")
[["vector": [...], 'text': 'hello world', 'id': 'deff1675-41ac-4190-b3b6-7ca9fde85c59', 'metadata': {'path': '/path/to/file'}, '_distance': 0.25669366121292114}]]
>>> memory.delete("deff1675-41ac-4190-b3b6-7ca9fde85c59")
>>> memory.count()
0
>>> memory.drop()
```

[MRG] add lancedb as memory

---

mle/cli.py
mle/utils/memory.py

Closes https://github.com/MLSysOps/MLE-agent/issues/270

[MRG] add mle memory crud api

---

mle/agents/planner.py
mle/model/ollama.py
mle/workflow/baseline.py

[MRG] ask users to provide absolute path and test deepseek

---

pyproject.toml

[MRG] Added the dependency for pyproject.toml

---

mle/utils/memory.py
pyproject.toml

Closes https://github.com/MLSysOps/MLE-agent/issues/298
Use the `Mem0` to store and retrieve long-term chat history in memory.
- `infer=True` enables automatic memory summarization.
- chat history is structured using role and content, compatible with OpenAI chat format.
- each memory entry is deduplicated via content hash and time-stamped for tracking.
```python
from mle.utils.memory import Mem0
mem = Mem0()
chat_sessions: list[dict[str, str]] = [
{"role": "system", "content": "You are a helpful assistant."},
{"role": "assistant", "content": "What is your favorite city?"},
{"role": "user", "content": "The capital of France, Paris."},
{"role": "assistant", "content": "Sure, I will remember for these"},
]
mem.add(chat_sessions, infer=True, prompt="Remember the information for the user") …
```

[MRG] add mem0 memory

---

mle/agents/advisor.py
mle/agents/debugger.py
mle/model/gemini.py

Closes #302
`advisor.py`
remove the duplicate [schema_web_search](https://github.com/MLSysOps/MLE-agent/blob/cf9762d3abd3cad227bbd859a3ef4f95dff164a3/mle/agents/advisor.py#L134)
`gemini.py` uses the `google-genai` SDK, highlights:
1. [gemini api migrate doc](https://ai.google.dev/gemini-api/docs/migrate#automatic-function) states the new SDK promotes a stateless approach as its primary interaction model, which is a significant change from the stateful sessions that were central to the old SDK. Specially, instead of [`model.start_chat`](https://github.com/MLSysOps/MLE-agent/blob/cf9762d3abd3cad227bbd859a3ef4f95dff164a3/mle/model/gemini.py#L111), now it's `client.models.generate_content()`
2. As pointed out in the [issue](https://github.com/MLSysOps/MLE-agent/issues/302#issuecomment-30553932 …

[MRG] feat(model): Update gemini.py to use new Gemini API
