MLSysOps/MLE-agent

README.md

[MRG] add warning and support llms

---

README.md

[MRG] add demo video

---

agent/cli.py
agent/function/code_gen_agent.py
agent/function/tech_leader.py
agent/types/base.py
requirements.txt

[MRG] user can set wandb, add mlops tool in prompt, fix small issues

---

README.md
agent/cli.py
agent/function/tech_leader.py
agent/integration/kaggle_workflow.py
agent/types/base.py
requirements.txt

[MRG] add vary basic kaggle workflow and fix some small issues

---

README.md

add kaggle mode to the readme

---

agent/cli.py

Closes https://github.com/MLSysOps/MLE-agent/issues/89

[MRG] quickfix: fail to run on non-kaggle environment

---

agent/cli.py
agent/function/__init__.py
agent/function/code_gen_agent.py
agent/function/code_retrieve_agent.py
agent/integration/__init__.py
agent/integration/github.py

closes https://github.com/MLSysOps/MLE-agent/issues/84
workflow:
1. generate at least five keywords related to user's projects
2. search the github repositories, and select at least three repos matched user's requirements
3. search the repo codes iteratively, and find the most relevant codes to enhance the code generation

[MRG] feat: search github codes to enhance the code generation

---

.github/workflows/pr_agent.yml

[MRG] Create pr_agent.yml

---

README.md

Closes #
___
documentation
___
- Updated the video link in the `README.md` file to a new URL.
- Removed the outdated video link from the `README.md` file.
___
<tr>
<td>
<details>
<summary><strong>README.md</strong><dd><code>Update video link in README.md</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
README.md
- Updated video link in the documentation.
- Removed old video link.
</details> …

add new video

---

mle/version.py

enhancement
___
- Updated the version number in `mle/version.py` from `0.2.1` to `0.3.0`.
___
<tr>
<td>
<details>
<summary><strong>version.py</strong><dd><code>Update version number to 0.3.0</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
mle/version.py
- Updated the version number from `0.2.1` to `0.3.0`.
</details>
</td>
<td><a href="https://github.com/MLSysOps/MLE-agent/pull/120/files#diff-acd9c1d9e32245b0d91b94eb26316907965bde9fddd18bcce1f1c5653a26db94">+1/-1</a>&nbsp; &nbsp; &nbsp; …

[MRG] build version v0.3.0

---

mle/utils/__init__.py
mle/utils/cache.py
mle/utils/system.py
mle/workflow/baseline.py

Closes https://github.com/MLSysOps/MLE-agent/issues/121 https://github.com/MLSysOps/MLE-agent/issues/122 

[MRG] add previous step&task resume

---

mle/agents/__init__.py
mle/agents/reporter.py
mle/cli.py
mle/utils/system.py
mle/workflow/__init__.py
mle/workflow/report.py

Enhancement
___
- Added a new `report` mode to the `mle start` command in the CLI.
- Implemented the `report` function in `mle.workflow.report` to handle the new mode.
- Integrated user prompts for dataset information and requirements.
- Utilized `AdviseAgent` to generate and display suggestions in a report format.
___
<tr>
<td>
<details>
<summary><strong>cli.py</strong><dd><code>Add report mode to CLI start function</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
mle/cli.py
<li>Added a new mode <code>report</code> to the …

[MRG] Improve advisor agent with markdown output

---

mle/integration/github.py

Enrich the github apis to fetch readme, repo metadata (e.g., license, contributors) and releases.

[MRG] Enrich the github apis

---

mle/cli.py
mle/integration/github.py
mle/integration/google_calendar.py
mle/utils/system.py
mle/workflow/report.py

Closes https://github.com/MLSysOps/MLE-agent/issues/148

[MRG] github & google calendar integrate command

---

README.md

1 milestone
1 just keep discord
Closes #
___
documentation
___
- Updated the milestone dates in the README to a consistent format and added a new milestone for "Kaia is born" on 07/03/2024.
- Simplified the contribution instructions by rephrasing the call to action.
- Clarified the license reference by specifying "MIT License" instead of a generic "LICENSE".
___
<tr>
<td>
<details>
<summary><strong>README.md</strong><dd><code>Update milestones and improve contribution and license sections</code></dd></summary>
<hr>
README.md
<li>Updated milestone dates to …

[MRG] update readme

---

mle/workflow/baseline.py

[MRG] fix typos

---

README.md
requirements.txt

RT
___
enhancement, documentation
___
- Updated the README to mark "Local RAG support" and "Anthropic Claude 3.5 Sonnet" tasks as completed.
- Removed the version constraint for the `onnxruntime` dependency in `requirements.txt`.
___
<tr>
<td>
<details>
<summary><strong>README.md</strong><dd><code>Update task completion status in README</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
README.md
<li>Marked "Local RAG support" task as completed.<br> <li> Marked "Anthropic Claude 3.5 Sonnet" task as completed.<br>
</details>
</td>
<td><a …

[MRG] finish some tasks in README and improve requirement

---

README.md

documentation
___
- Added a trending badge to the `README.md` file to enhance visibility and provide insights into the repository's activity.
- The badge links to Trendshift, offering users a quick way to view the repository's trends.
___
<tr>
<td>
<details>
<summary><strong>README.md</strong><dd><code>Add trending badge to README for visibility</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
README.md
<li>Added a trending badge to the README.<br> <li> Badge links to Trendshift for repository insights.<br>
</details>
</td>
<td><a …

[MRG] Adding trending badge to README.md

---

mle/agents/reporter.py
mle/agents/summarizer.py
mle/cli.py
mle/integration/github.py
mle/integration/google_calendar.py
mle/utils/system.py
mle/workflow/report.py

___
Enhancement, Bug fix
___
- Refactored `ReportAgent` to focus on generating progress reports, removing ML task suggestion functionalities.
- Enhanced integration logic for GitHub and Google Calendar, including checks for existing tokens.
- Updated model loading to use "gpt-4o" in the CLI.
- Improved Google Calendar integration with better error handling and date processing.
- Made minor formatting improvements for better code readability.
___
<tr>
<td>
<details>
<summary><strong>reporter.py</strong><dd><code>Refactor ReportAgent for Progress Report Generation</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
mle/agents/reporter.py …

[MRG] Implementation the initial report agent

---

mle/agents/coder.py
mle/agents/debugger.py
mle/model.py

Closes https://github.com/MLSysOps/MLE-agent/issues/160

[MRG] fix: generate no code

---

mle/agents/advisor.py
mle/utils/system.py
mle/workflow/baseline.py

closes: https://github.com/MLSysOps/MLE-agent/issues/159

[MRG] suggest datasets if user's input is unclear 

---

MANIFEST.in
mle/cli.py
mle/utils/system.py

closes: https://github.com/MLSysOps/MLE-agent/issues/182

[MRG] combile pnpm dev and mle serve within `mle report`

---

mle/version.py

enhancement
___
- Updated the version number in `mle/version.py` from `0.3.1` to `0.4.0` to reflect the new build version.
___
<tr>
<td>
<details>
<summary><strong>version.py</strong><dd><code>Update version number to v0.4.0</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
mle/version.py
- Updated the version number from `0.3.1` to `0.4.0`.
</details>
</td>
<td><a href="https://github.com/MLSysOps/MLE-agent/pull/208/files#diff-acd9c1d9e32245b0d91b94eb26316907965bde9fddd18bcce1f1c5653a26db94">+1/-1</ …

[MRG] build version v0.4.0

---

README.md

Closes #
___
documentation
___
- Updated the README to include a new milestone for the release of version 0.4.0.
- Highlighted new command-line interfaces (CLIs) such as `MLE report`, `MLE kaggle`, and `MLE integration`.
- Mentioned the introduction of new models like `Mistral`.
___
<tr>
<td>
<details>
<summary><strong>README.md</strong><dd><code>Add milestone for version 0.4.0 release in README</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
README.md
<li>Added a new milestone for the release of version 0.4.0.<br> <li> …

[MRG] update readme for 0.4.0

---

mle/model.py
mle/utils/data.py
mle/utils/system.py
requirements.txt

Closes https://github.com/MLSysOps/repx-agent/issues/30

[MRG] add langfuse

---

mle/model.py

Closes https://github.com/MLSysOps/MLE-agent/issues/174
```bash
export OPENAI_BASE_URL=<proxy_url>
mle start
```

[MRG] add manual openai base_url

---

README.md

[MRG] update README.md

---

mle/agents/__init__.py
mle/agents/chat.py
mle/agents/coder.py
mle/cli.py
mle/utils/cache.py
mle/workflow/__init__.py
mle/workflow/baseline.py
mle/workflow/chat.py
mle/workflow/kaggle.py

Closes https://github.com/MLSysOps/MLE-agent/issues/205

[MRG] redesign `mle chat`

---

mle/integration/__init__.py
mle/integration/local_git.py
requirements.txt

-  `get_repo_status`: returns the git status, if files have been changed, show the author, the date, and the changed filename.
- `get_commit_history`: returns the git commit history, with the parameter `limit` can set the limit of the term number. Node code diff will be shown.
- `get_commit_diff`: get the git commit details by giving a commit hash, you can choose whether to return the changed contents, or just showing the metadata.
In the next I am going to integrate those metadata into an LLM agent

[MRG] Added the local .git metadata fetchers

---

mle/version.py

[MRG] Built version v0.4.2

---

mle/agents/advisor.py

[MRG] quickfix: miss list_files function

---

mle/cli.py
requirements.txt

[MRG] Fixed the memory init before config error

---

mle/cli.py
mle/model/__init__.py
mle/model/vllm.py

[MRG] 🚑 quickfix: fixed the lint issues

---

.github/workflows/lint.yml
.github/workflows/test.yml
README.md

Add citation

---

pyproject.toml

Update the LICENSE in the `pyproject.toml` to avoid the installation error while running `pip install -e .`

[MRG] Fixed the installation issue

---

pyproject.toml

[MRG] 🚑 quickfix: fixed the dependency versioning
